# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7393bc8fc734b342ca78172be29e493337097b879daa8b6157f95b60ade64ae6f842159f2037eb81917c8d51504686d7d27d94515257f5371cc0fbf50aeb1cf

test:
  secret_key_base: d04687e4481392744ce15af99936b7dc4f7987dbd347de9a7ebab28d5a00b903281994bad0f940024746a8a89dd008aeda920386005db492fc8ff3528cce7df8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
